feature: NEW gradle.yml 구현

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,6 +1,5 @@
-
 # github repository actions 페이지에 나타날 이름
-name: CI/CD using github actions & docker
+name: CI/CD
 
 # event trigger
 # master이나 dev 브랜치에 push가 되었을 때 실행
@@ -12,13 +11,10 @@ permissions:
   contents: read
 
 jobs:
-  CI-CD:
+  build:
     runs-on: ubuntu-latest
     steps:
-      - name: Add Docker CLI to PATH
-        run: echo "${{ runner.temp }}/usr/bin" >> $GITHUB_PATH
-
-      # JDK setting - github actions에서 사용할 JDK 설정 (프로젝트나 AWS의 java 버전과 달라도 무방)
+      # JDK setting
       - uses: actions/checkout@v3
       - name: Set up JDK 17
         uses: actions/setup-java@v3
@@ -26,70 +22,84 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
-      # gradle caching - 빌드 시간 향상
-      - name: Gradle Caching
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.gradle/caches
-            ~/.gradle/wrapper
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-          restore-keys: |
-            $-gradle-
-
-      # 환경별 yml 파일 생성 - application.yml
-      - name: make application.yml
-        if: |
-          contains(github.ref, 'master') ||
-          contains(github.ref, 'dev')
-        run: |
-          mkdir -p ./src/main/resources
-          echo "${{ secrets.YML }}" > ./src/main/resources/application.yml
-        shell: bash
-
-      # gradlew 스크립트에 실행 권한 부여
-      - name: gradlew 스크립트에 실행 권한 부여
+      - name: Build with Gradle
         run: |
           chmod +x ./gradlew
+          ./gradlew build -x test
 
-      # gradle build
-      - name: Build with Gradle
-        run: ./gradlew build -x test
-
-      # docker build & push to production
-      - name: Docker build, and push to prod
-        if: |
-          contains(github.ref, 'master') ||
-          contains(github.ref, 'dev')
-        run: |
-          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/eroom-prod .
-          docker push ${{ secrets.DOCKER_USERNAME }}/eroom-prod
-
-      ## pull to production
-      - name: Pull to prod
-        uses: appleboy/ssh-action@master
-        id: pull-prod
-        if: |
-          contains(github.ref, 'master') ||
-          contains(github.ref, 'dev')
+      - name: Login to DockerHub
+        uses: docker/login-action@v1
         with:
-          host: ${{ secrets.HOST_PROD }} # EC2 퍼블릭 IPv4 DNS
-          username: ${{ secrets.USERNAME }} # ubuntu
-          port: 22
-          key: ${{ secrets.PRIVATE_KEY }}
-          envs: GITHUB_SHA
-          script: |
-            sudo docker ps
-            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/eroom-prod
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-  docker-pull-and-run:
-    runs-on: [self-hosted, prod]
-    if: ${{ needs.CI-CD.result == 'success' }}
-    needs: [ CI-CD ]
+      - name: Build Docker
+        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/eroom-prod .
+      - name: Push Docker
+        run: docker push ${{ secrets.DOCKER_USERNAME }}/eroom-prod:latest
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
     steps:
-      - name : 배포 스크립트 실행
+      - name: Set target IP
         run: |
-          sh /home/ubuntu/deploy.sh
-          sudo docker image prune -f
-          
+          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.HOST_PROD }}/env")
+          echo $STATUS
+          if [ $STATUS = 200 ]; then
+            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.HOST_PROD }}/env")
+          else
+            CURRENT_UPSTREAM=green
+          fi
+          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
+          if [ $CURRENT_UPSTREAM = blue ]; then
+            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+          elif [ $CURRENT_UPSTREAM = green ]; then
+            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+          else
+            echo "error"
+            exit 1
+          fi
+
+      - name: Docker compose
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.HOST_PROD }}
+          key: ${{ secrets.PRIVATE_KEY }}
+          script_stop: true
+          script: |
+            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/eroom-prod:latest
+            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d
+
+      - name: Check deploy server URL
+        uses: jtalk/url-health-check-action@v3
+        with:
+          url: http://${{ secrets.HOST_PROD }}:${{env.STOPPED_PORT}}/env
+          max-attempts: 5
+          retry-delay: 10s
+
+      - name: Change nginx upstream
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.HOST_PROD }}
+          key: ${{ secrets.PRIVATE_KEY }}
+          script_stop: true
+          script: |
+            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc && nginx -s reload' 
+
+      - name: Stop current server
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.HOST_PROD }}
+          key: ${{ secrets.PRIVATE_KEY }}
+          script_stop: true
+          script: |
+            sudo docker stop ${{env.CURRENT_UPSTREAM}}
+            sudo docker rm ${{env.CURRENT_UPSTREAM}}
